/**
 * Generates WAV fixtures for Playwright's fake microphone
 * (--use-file-for-fake-audio-capture). Deterministic, committed nowhere —
 * regenerated by pretest:e2e.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "generated");
mkdirSync(outDir, { recursive: true });

const SAMPLE_RATE = 48000;

function wav(samples) {
  const data = Buffer.alloc(samples.length * 2);
  samples.forEach((v, i) => data.writeInt16LE(Math.max(-1, Math.min(1, v)) * 32767, i * 2));
  const header = Buffer.alloc(44);
  header.write("RIFF", 0);
  header.writeUInt32LE(36 + data.length, 4);
  header.write("WAVE", 8);
  header.write("fmt ", 12);
  header.writeUInt32LE(16, 16);
  header.writeUInt16LE(1, 20); // PCM
  header.writeUInt16LE(1, 22); // mono
  header.writeUInt32LE(SAMPLE_RATE, 24);
  header.writeUInt32LE(SAMPLE_RATE * 2, 28);
  header.writeUInt16LE(2, 32);
  header.writeUInt16LE(16, 34);
  header.write("data", 36);
  header.writeUInt32LE(data.length, 40);
  return Buffer.concat([header, data]);
}

function tone(freq, seconds, gain = 0.5) {
  const n = Math.floor(SAMPLE_RATE * seconds);
  const out = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    const t = (2 * Math.PI * freq * i) / SAMPLE_RATE;
    // Mild harmonics so it resembles a plucked string more than a beep.
    out[i] = gain * (0.7 * Math.sin(t) + 0.2 * Math.sin(2 * t) + 0.1 * Math.sin(3 * t));
  }
  return out;
}

// 15s of in-tune E2 — long enough for signal (300ms) + hold (1500ms) with margin.
writeFileSync(join(outDir, "e2-in-tune.wav"), wav(tone(82.41, 15)));

// E2 slightly flat (-30 cents): needle must read "too low", never stabilize.
writeFileSync(
  join(outDir, "e2-flat.wav"),
  wav(tone(82.41 * Math.pow(2, -30 / 1200), 15)),
);

console.log(`fixtures written to ${outDir}`);
